### ISSUE TITLE
Js в pug

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#12]
Весь js нужно держать в своих js-файлах, не стоит помещать его непосредственно в pug/html. Здесь, по всей видимости, это js от блока `loader`, значит, в его папке он и должен находиться.

![Снимок экрана в 2019-10-14 22-18-39](https://user-images.githubusercontent.com/38564412/66777235-24885200-eed1-11e9-8cb4-c5222fcc6aea.png)

**Comment by viktoriya-ch** [comment]
Вот так подключать скрипты тоже не очень - у тебя ведь есть один общий js-файл, в который webpack всё собирает, он подключается в конце страницы, туда же и карты должны подтягиваться.

![Снимок экрана в 2019-10-14 22-33-30](https://user-images.githubusercontent.com/38564412/66777931-f441b300-eed2-11e9-9a54-9d2d29e145c4.png)

**Comment by imin314** [comment]
Скрипт для карты перенесла.
С лоадером пришлось помучаться. Была проблема с тем, чтобы скрыть html перед тем, как загрузятся стили. 
В общем, с помощью плагина HtmlWebpackInjector подключила js в тег head.
Сам блок loader удалила, потому что по сути он появляется там на мгновение.

**Comment by viktoriya-ch** [comment]
Сейчас поломалась сборка

![Снимок экрана в 2019-10-17 20-46-22](https://user-images.githubusercontent.com/38564412/67033827-33644400-f11f-11e9-99b6-a014e1f026a8.png)

**Comment by viktoriya-ch** [comment]
И еще что-то с home случилось, появилась полоса прокрутки

![Снимок экрана в 2019-10-17 20-49-37](https://user-images.githubusercontent.com/38564412/67034100-bd141180-f11f-11e9-8cc6-06bb7e5ab6a1.png)

**Comment by imin314** [comment]
Поправила. Проект не запускался из-за неправильного пути импорта (windows почему-то не ругался на обратные слэши).
Ширину тоже поправила.
