### ISSUE TITLE
Отступы

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#13]
По стандартам используем отступы пробелами, сейчас вот тут у тебя оказался таб, и это сразу визуально видно. Нужно посмотреть по всему проекту 

![Снимок экрана в 2019-10-14 22-24-34](https://user-images.githubusercontent.com/38564412/66777396-995b8c00-eed1-11e9-9356-1680e4956490.png)

**Comment by imin314** [comment]
Поправила глобально
