### ISSUE TITLE
Тэги без классов

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#14]
По стандартам, все тэги должны иметь свои классы, пункт 11: https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md

Использование селекторов тэгов в css также противоречит БЭМ

![Снимок экрана в 2019-10-14 22-42-21](https://user-images.githubusercontent.com/38564412/66778376-23a4ef80-eed4-11e9-9321-3846e094029d.png)

![Снимок экрана в 2019-10-14 22-44-44](https://user-images.githubusercontent.com/38564412/66778409-3c150a00-eed4-11e9-8ba0-67b47164dfc8.png)

**Comment by imin314** [comment]
Проверила глобально в проекте
