### ISSUE TITLE
Оформление блоков кода в pug

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#15]
Есть предложение писать блоки кода вот так

![Снимок экрана в 2019-10-17 20-57-04](https://user-images.githubusercontent.com/38564412/67034635-b3d77480-f120-11e9-8f0d-cb0b48231bdf.png)

А не вот так

![Снимок экрана в 2019-10-17 20-57-48](https://user-images.githubusercontent.com/38564412/67034677-cb166200-f120-11e9-8eca-c75cb8c2c083.png)

Читается сразу гораздо легче)

**Comment by imin314** [comment]
Я не знала, что так можно х) Спасибо, теперь стало гораздо читабельней
