### ISSUE TITLE
Инициализация компонентов

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#16]
Создание инстансов лучше перенести в отдельные файлы, например, init.js положить рядом в папку блока. А то у тебя получается, что ты описываешь класс и тут же его создаешь, хотя теоретически он может использоваться и создаваться где угодно, импортироваться в другие блоки и т.д.

![Снимок экрана в 2019-10-17 21-04-16](https://user-images.githubusercontent.com/38564412/67035136-bb4b4d80-f121-11e9-97a7-2025a6c56cce.png)

**Comment by imin314** [comment]
Вынесла инициализацию в отдельные файлы.
Почему-то eslint отвалился и не хотел работать, пока локально не установила. Только я сомневаюсь, что нужно в package.json добавлять eslint.

**Comment by viktoriya-ch** [comment]
Ну вообще-то да, он должен быть в package.json, и про локальную установку, кстати, есть в стандартах:

> В проекте должно быть использовано по минимуму глобальных библиотек, все они должны быть перечислены в Readme (webpack, karma и все, что может быть поставлено через npm точно не должно быть глобальным);

https://github.com/fullstack-development/front-end-best-practices/blob/master/Initiation.md
