### ISSUE TITLE
Выносить обработчики событий в отдельные функции

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#17]
По стандартам, обработчики событий выносятся  в отдельные функции: пункт 11 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

![Снимок экрана в 2019-10-17 21-12-42](https://user-images.githubusercontent.com/38564412/67035728-dff3f500-f122-11e9-9463-f00164e6102f.png)

Чтобы не потерять контекст, есть разные способы, не обязательно здесь оборачивать обработчик в дополнительную функцию

![Снимок экрана в 2019-10-17 21-10-48](https://user-images.githubusercontent.com/38564412/67035654-b8049180-f122-11e9-8d10-d04d3728be95.png)

**Comment by imin314** [comment]
Начала вносить правку. Можешь, пожалуйста, проверить, подойдет ли такое решение?

**Comment by imin314** [comment]
Немного поправила методы initialize в блоках - теперь document.ready не в классе, а снаружи при инициализации в init.js

**Comment by viktoriya-ch** [comment]
Да, такое решение вполне подходит и здесь, думаю, оптимально, хотя есть еще альтернативы (про это как раз будет в собеседовании). А в твоем случае можно немного улучшить всё, добавив декоратор `@bind`

**Comment by viktoriya-ch** [comment]
И еще, обработчики событий именуются по шаблону `handleElementNameEventName`, у тебя в примере ниже первый обработчик правильно назван, а вот с остальными уже не так:

![Снимок экрана в 2019-10-21 21-34-14](https://user-images.githubusercontent.com/38564412/67232732-9c62f900-f44a-11e9-8606-3b07e213fadb.png)

**Comment by imin314** [comment]
Добавила декоратор @bind, переименовала обработчики событий, но есть сомнения в случаях, когда один обработчик вешается на события разных элементов:
![Screenshot_1](https://user-images.githubusercontent.com/40715953/67354108-70e12b00-f57e-11e9-9068-732e8dfbeb19.png)

**Comment by viktoriya-ch** [comment]
Если нужен один и тот же код в обработчиках, он выносится в функцию, а далее эта функция вызывается в соответствующем обработчике каждого элемента.

**Comment by imin314** [comment]
Для кнопок на карте изменила название элементов. Теперь это не два разных элемента search и pin, а модификаторы для .map__button. И в js теперь один раз только добавляется обработчики по клику и keypress.
