### ISSUE TITLE
Использовать переменные для цвета

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#18]
Все цвета, которые используются в диаграммах, встречаются на всем проекте. Поэтому тут логичнее было бы использовать переменные в stylus и модификаторы для этих элементов / блоков. Если где-то еще вот так напрямую задаются цвета, уже имеющиеся в цветовой схеме, лучше также переделать.

![Снимок экрана в 2019-10-17 21-22-00](https://user-images.githubusercontent.com/38564412/67036457-5d6c3500-f124-11e9-8335-3ed5008c5735.png)

**Comment by imin314** [comment]
При таком подходе пришлось добавить миксин для вычисления цвета сегментов диаграммы. Просто если, например, надо будет нарисовать диаграмму для 6 значений, то цветов не хватит))

**Comment by viktoriya-ch** [comment]
Да, цветов бы не хватило, но я думаю, что они в теории должны браться из палитры, по крайней мере, те, что есть на макете, взяты из палитры. Ну с миксином тоже хорошо)
