### ISSUE TITLE
Методы

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#19]
По стандартам, метод должен выполнять только одну задачу и должен быть компактным. Пункт 4 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

Например, вот здесь у тебя почти что весь код класса оказался в одном методе `_drawDonut()`. Возможно, стоит подумать о том, как его разбить на более мелкие методы, которые бы занимались каждый своей задачей.

![Снимок экрана в 2019-10-17 21-32-01](https://user-images.githubusercontent.com/38564412/67037387-12ebb800-f126-11e9-9961-5bdb0c1d54cf.png)

**Comment by viktoriya-ch** [comment]
Заодно тут же, чтобы не создавать отдельное ишью - откуда взялась эта цифра?)

![Снимок экрана в 2019-10-17 21-36-39](https://user-images.githubusercontent.com/38564412/67037484-46c6dd80-f126-11e9-844c-15879580a89c.png)

**Comment by imin314** [comment]
Поправила оба ишьюза по диаграммам в одном коммите.
Решила все-таки отрефакторить имеющийся код, а не разбираться с плагинами.

По поводу непонятных цифр. Делала на основе статьи [Scratch-made SVG Donut & Pie Charts in HTML5](https://medium.com/@heyoka/scratch-made-svg-donut-pie-charts-in-html5-2c587e935d72).
Автор принимает длину круга равной 100. Из геометрии _c = 2 х pi х r_, откуда следует, что радиус равен 15.915....
Добавила комментарий в код с пояснением.

**Comment by viktoriya-ch** [comment]
> Добавила комментарий в код с пояснением

Да, это точно требует пояснений. В целом код должен быть понятен и без комментариев, но если где-то есть вот такие неочевидные вещи и нет альтернатив, то, думаю, комментарии нужны.
