### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#2]
В макете у кнопок в нажатом состоянии нет нижней тени
![Снимок экрана в 2019-10-01 23-21-15](https://user-images.githubusercontent.com/38564412/65997568-4978d000-e4a2-11e9-856b-d90a6e6a1970.png)

**Comment by imin314** [comment]
Поправила целиком блок button и добавила тень в нажатом состоянии, но, кстати, в макете-то тени не было.
![buttons](https://user-images.githubusercontent.com/40715953/66027584-699da300-e525-11e9-9b37-3d71e9741397.png)

**Comment by viktoriya-ch** [comment]
Ну да, я как раз и написала, что в зажатом состоянии тени в макете нет, то есть кнопка должна как бы "вдавливаться", а у тебя она на месте остается.

Если бы тень убиралась, то это бы выглядело так:

![button](https://user-images.githubusercontent.com/38564412/66030614-66e18480-e50a-11e9-8c61-37a33b2efefe.gif)

**Comment by imin314** [comment]
Поняла:) Вроде поправила, как надо теперь. Случайно в коммит включила лишние файлы.

**Comment by viktoriya-ch** [comment]
Сейчас почему-то не каждый раз срабатывает)

![Peek 2019-10-03 09-38](https://user-images.githubusercontent.com/38564412/66104628-df574c80-e5c1-11e9-89c5-05129ad35c29.gif)

**Comment by imin314** [comment]
Пришлось заменить плагин. Сейчас должно работать, как надо.
