### ISSUE TITLE
Toggle, tickbox

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#20]
А почему переключатели и чекбоксы js-ом сделаны? Вроде у тебя тут ничего такого в них не реализовано, что нельзя было бы сделать при помощи html+css

**Comment by imin314** [comment]
Да, сами элементы работают без js. Добавила, чтобы после нажатия убирался фокус и чтобы они срабатывали при нажатии Enter. Возможно это лишнее.

**Comment by viktoriya-ch** [comment]
А, ну тогда можно оставить)
