### ISSUE TITLE
Ширина кнопок

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#21]
Мне кажется, жестко задавать ширину кнопок не совсем правильно - внутри кнопки может быть какой угодно текст, и он может не поместиться. 

![Снимок экрана в 2019-10-21 21-45-49](https://user-images.githubusercontent.com/38564412/67233578-2f506300-f44c-11e9-8e97-338df4757091.png)

**Comment by imin314** [comment]
Поправила. Теперь ширина кнопок задается элементом-оберткой

**Comment by viktoriya-ch** [comment]
Ну мне кажется, суть не особо изменилась, потребуется менять текст кнопок и текст окажется длиннее, чем есть сейчас - придется менять ширину у оберток. Может, лучше это паддингами сделать? Еще можно указать минимальную ширину кнопки, если паддинги для кнопок по макету получатся слишком большие.
