### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#22]
Названия блоков arrow-section, button-section и т.п. переводятся как "секция стрелки", "секция кнопки", но в секции ведь не одна кнопка/стрелка лежит, их несколько?)

![Снимок экрана в 2019-10-27 19-14-57](https://user-images.githubusercontent.com/38564412/67637695-19c8b680-f8ee-11e9-90c3-5e2d6dbe97ff.png)

**Calendar.js**
Вот здесь, мне кажется, не очень удачное название методов, поменяется реализация - и слово `prepend/append` в названии может стать неактуальным

![Снимок экрана в 2019-10-27 19-15-55](https://user-images.githubusercontent.com/38564412/67637721-63190600-f8ee-11e9-8fe7-51e71085fcba.png)

**Comment by viktoriya-ch** [comment]
**DonutChart.js**

А почему здесь в названии методов в начале используется $? У нас вроде в стандартах нигде нет такого)

![Снимок экрана в 2019-10-27 19-25-10](https://user-images.githubusercontent.com/38564412/67637851-97d98d00-f8ef-11e9-8640-ce330f4aa172.png)

**Comment by imin314** [comment]
Названия prepend/append поменяла и $ перед методами удалила.
А по поводу названий блоков arrow-section и т.п. Первое слово по правилам грамматики английского языка не может стоять во множественном числе, но в коде, пожалуй, важнее, чтобы всем был понятен смысл названия, поэтому могу поменять всё на множественное число.

**Comment by viktoriya-ch** [comment]
> А по поводу названий блоков arrow-section и т.п. Первое слово по правилам грамматики английского языка не может стоять во множественном числе

Хм, а вот этого не знала, тогда наверное лучше так оставить)

**Comment by viktoriya-ch** [comment]
Первый, второй, третий - это ведь не булевы модификаторы?

![Снимок экрана в 2019-10-29 10-47-16](https://user-images.githubusercontent.com/38564412/67747354-9320f000-fa39-11e9-9447-4ba6f47ab598.png)

И название модификатора, мне кажется, не очень удачное: они отличаются не только тем, что они имеют какой-то порядковый номер, и к тому же могут поменяться местами.

**Comment by imin314** [comment]
Убрала вообще модификаторы в этом месте. Мне кажется, я неправильно их использовала - они по сути нужны были только для позиционирования дочерних элементов. Сейчас добавила дополнительные контейнеры вместо модификаторов.

**Comment by imin314** [comment]
Забыла референс в коммите оставить.
[registration-form stage modifiers removed #22](https://github.com/imin314/FlatUI_project/commit/8f85ec5ea61cd9d87e05e71077ab692f9ac0b6c4)

**Comment by viktoriya-ch** [comment]
Здесь, мне кажется, не совсем удачные названия модификаторов. Во-первых, если перевести, получается "тип подсказка" и "тип шкала", бессмыслица. Во-вторых, это, скорее, булевы модификаторы, они друг с другом никак не связаны, группировать их вместе с одним ключом `_type_` думаю, некорректно, они каждый сам по себе. Тем более, что один модификатор не исключает другой, они могут присутствовать оба одновременно. И у каждого имеет значение только его наличие/отсутствие. Есть подсказка - нет подсказки, есть шкала - нет шкалы. 

![Снимок экрана в 2019-11-04 11-15-56](https://user-images.githubusercontent.com/38564412/68107196-1ab4a600-fef5-11e9-8849-7873b9fcc2a9.png)

**Comment by imin314** [comment]
Поправила модификаторы для слайдера
