### ISSUE TITLE
Отрицательные margin

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#23]
По стандартам, следует избегать отрицательных марджинов, нужно проверить по всему проекту, где еще это встречается:

Пункт 4 https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/rules.md

![Снимок экрана в 2019-10-28 09-14-06](https://user-images.githubusercontent.com/38564412/67655909-4ec32080-f963-11e9-8496-f732fa813472.png)

**Comment by imin314** [comment]
Упустила этот маржин во время рефакторинга. Не понимаю, зачем его поставила сначала, он ничего не менял)

**Comment by imin314** [comment]
По всему проекту проверила, был единственный
