### ISSUE TITLE
Checkboxes, toggles реализовать на чистом CSS

### ISSUE THREAD

**Issue by Sergio-Ka** [imin314/FlatUI_project#26]
Все, что может быть реализовано на чистом CSS, должно быть реализовано на нем. Об этом написано в стандартах. На счет остального возможно и допустимо использовать js, но эти две вещи точно должны быть без него.

**Comment by imin314** [comment]
Я старалась по максимуму следовать этому принципу, где могла. В js для чекбоксов и переключателей только код для поддержки переключения с помощью Enter и удаления фокуса после. Вика вроде сказала, что можно оставить его.

**Comment by Sergio-Ka** [comment]
Ок тогда.
