### ISSUE TITLE
Захардкоженность

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#27]
Сейчас в некоторых местах есть захардкоженность, например, заголовки секций можно поменять, только если полезть в миксин самих секций. Нужно по всему проекту посмотреть, и поправить моменты, где по идее должна быть возможность что-то поменять. 

![Снимок экрана в 2019-10-29 09-21-11](https://user-images.githubusercontent.com/38564412/67742556-767ebb00-fa2d-11e9-8025-763a970d91ed.png)

**Comment by imin314** [comment]
Но это ведь заголовки именно для блоков с мессенджером и кнопками, например,.
Если понадобится изменить название секции, то только если само содержимое блока изменится.

**Comment by viktoriya-ch** [comment]
> Если понадобится изменить название секции, то только если само содержимое блока изменится.

Ну не обязательно, в теории может быть такое, что нужно будет переименовать `standart buttons` на просто `buttons`, или вместо `standart` что-то другое написать, добавить какие-то уточнения в заголовок, и т. п. Это учебный проект, но в реальности заголовки секций запросто могут меняться без изменения содержания самой секции.

**Comment by viktoriya-ch** [comment]
В слайдере захардкожены min. max, step и value. 

![Снимок экрана в 2019-11-04 11-38-38](https://user-images.githubusercontent.com/38564412/68108115-edb5c280-fef7-11e9-87d3-2ffe305dae0b.png)

**Comment by imin314** [comment]
Вынесла настройки слайдера в параметры миксина.
