### ISSUE TITLE
newsCard

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#28]
Мне кажется, этот компонент нуждается в рефакторинге, уж очень много всего тут получилось. Как минимум, желательно хотя бы разделять код на смысловые части, отбивая пустыми строками, а то сейчас все просто в кучу, очень сложно читается. 

JS это тоже касается, в airbnb, кстати, написано, что нужно отделять блоки кода пустыми строками https://github.com/airbnb/javascript#whitespace--after-blocks.

Если есть идеи, как этот компонент упростить, то будет замечательно. Возможно, тернарники в атрибутах помогут, или еще что-то.

![Снимок экрана в 2019-10-29 10-30-30](https://user-images.githubusercontent.com/38564412/67746245-273d8800-fa37-11e9-97b9-f6704518f190.png)

По стандартам airbnb рекомендуется использовать шаблонные строки вместо конкатенации, мне кажется, у тебя много где такое попадалось, надо проверить: 

https://github.com/airbnb/javascript#es6-template-literals

![Снимок экрана в 2019-10-29 10-30-58](https://user-images.githubusercontent.com/38564412/67746288-3b818500-fa37-11e9-8bd6-d4c59759900f.png)

**Comment by imin314** [comment]
Разбила пустыми строками на смысловые части и убрала конкатенацию. Что-то другое придумать не смогла. Вроде всё по делу. Единственное - могу избавиться от модификаторов, reverted и compact, потому что они мне нужны только в двух местах сайта. А скролбар сделать по умолчанию без модификатора.

Кстати, я вроде проверила и в других файлах использовала шаблонные строки. Или вот такие случаи тоже исправить: ``className += ` ${sizeModifiers[size]}`;``?

**Comment by viktoriya-ch** [comment]
> Кстати, я вроде проверила и в других файлах использовала шаблонные строки. Или вот такие случаи тоже исправить

Ну если больше нигде нет, то хорошо.
Нет, тут речь о том, что если тебе часть строки надо высчитать или использовать в ней переменную, то нужно использовать шаблонные строки, в которых ты помещаешь код между `${}`, а не сложение строки и переменной / результата функции и т.п..

**Comment by imin314** [comment]
А по этому ишьюзу будут еще замечания?
