### ISSUE TITLE
speaker-carousel

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#29]
У ссылки нет обязательного атрибута href. Может, это и не ссылка?

![Снимок экрана в 2019-11-06 17-54-19](https://user-images.githubusercontent.com/38564412/68308930-b7766f80-00be-11ea-9aee-fc445f61cb89.png)

**Comment by imin314** [comment]
Да, это, пожалуй, и не ссылка вовсе) Поправила в нескольких местах, правда есть сомнения - не нужно ли использовать <button> в этих случаях?

**Comment by viktoriya-ch** [comment]
В случае с `arrow-button`, я думаю, что это скорее тэг `<button>`, вряд ли она на какой-то конкретный url будет вести. Хотя, в пагинации там возможны и ссылки, а вот в каком-нибудь слайдере arrow это `<button>`, так что мне кажется, тут есть смысл сделать тэг по умолчанию и добавить возможность поменять его через параметры миксина.

**Comment by viktoriya-ch** [comment]
В `speaker-carousel` мне кажется, это тоже кнопка, а не просто див.
