### ISSUE TITLE
Sliders

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#3]
У этого слайдера бегунок должен двигаться только по значениям шкалы

![Снимок экрана в 2019-10-01 23-22-59](https://user-images.githubusercontent.com/38564412/65997693-7c22c880-e4a2-11e9-9456-108d9495fa29.png)

**Comment by imin314** [comment]
Пришлось целиком переписать слайдер с jQuery-ui, потому что изначально выбрала неудачный плагин за основу. 
Кстати, если использую плагин, можно же самой стили все с нуля писать?

**Comment by viktoriya-ch** [comment]
> Кстати, если использую плагин, можно же самой стили все с нуля писать?

Не совсем понятен вопрос, можно поподробней?) Ты имеешь ввиду, добавить плагину свои классы и с их помощью стилизовать?

**Comment by imin314** [comment]
Я почему-то когда начинала делать это задание год назад, решила, что нужно искать плагины максимально похожие дизайном на элементы из макета. Поэтому получилось, что выбрала плагины, перегруженные стилями, которые потом долго подгоняла еще под макет.

И только сегодня, когда переписывала слайдер, до меня дошло, что из плагина же можно подключить только js, а исходные css не использовать. Так ведь?

**Comment by viktoriya-ch** [comment]
Ну да, если плагин позволяет это удобно сделать, то это идеальный вариант, как мне кажется)

**Comment by imin314** [comment]
Поправила это тоже.
