### ISSUE TITLE
Упростить файловую структуру

### ISSUE THREAD

**Issue by Sergio-Ka** [imin314/FlatUI_project#30]
В блоках common.blocks тех, что БЭМ (компонентах читай) есть папки js, styl, img - в зависимости от блока. Если в img еще есть смысл, так как рисунков в рамках блока может быть много, то как правило в блоке один файл структуры, один скриптовый и один стилевой (в повседневной работе с React 1 файл .tsx в котором и структура и скрипты, 1 стилевой). Потому искусственно усложнять структуру смысла нет здесь. Это только усложняет хождение по проекту и восприятие, а профита с этого никакого. Поэтому папки js, styl по всем блокам прибрать. У тебя все равно функция в точке входа это все собирает автоматом.

**Comment by imin314** [comment]
Поправила
