### ISSUE TITLE
Form elemnts

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#4]
Мне кажется, тут лучше бы было растягивать поля на всю ширину, когда они не провалидированы, чтобы не было пустоты

![Снимок экрана в 2019-10-01 23-25-09](https://user-images.githubusercontent.com/38564412/65997849-d754bb00-e4a2-11e9-96ca-d6dddc636d6a.png)

**Comment by imin314** [comment]
По этой ишью тоже правки внесла.
