### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#5]
На ширине экрана примерно от 960 пикселей начинает разъезжаться всё в разные стороны, может, стоит ограничить максимальную ширину?

Пример:

![Снимок экрана в 2019-10-01 23-31-02](https://user-images.githubusercontent.com/38564412/65998226-8d200980-e4a3-11e9-847e-2753f5973bae.png)

**Comment by imin314** [comment]
Эту проблему устранила в рамках работы над ишью #8.
