### ISSUE TITLE
Сборка проекта

### ISSUE THREAD

**Issue by viktoriya-ch** [imin314/FlatUI_project#7]
Ты, видимо, меняла имена файлов с шрифтами, но в репозитории они остались со старыми именами, из-за чего сейчас не собирается проект:

![Снимок экрана в 2019-10-02 21-17-47](https://user-images.githubusercontent.com/38564412/66070503-1bef5d80-e55a-11e9-8599-f5a873c49cce.png)

![Снимок экрана в 2019-10-02 21-18-48](https://user-images.githubusercontent.com/38564412/66070593-43462a80-e55a-11e9-9a3f-c240d474b1a0.png)

**Comment by imin314** [comment]
Поправила. Все-таки Linux более требовательный:)
